# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for Linayang driver
#

obj-$(CONFIG_LY_EARLY_WATCHDOG) += ly_early_watchdog.o
obj-$(CONFIG_LY_ST75161) += ly_st75161.o
obj-$(CONFIG_LY_POWER) += ly_power.o
obj-$(CONFIG_LY_WATCHDOG) += ly_watchdog.o
obj-$(CONFIG_LY_HT7132) += ly_ht7132.o
